language: objective-c
osx_image: xcode9
before_install:
  - gem install pact-mock_service -v 2.1.0
  - bundle install
  - brew update
  - brew upgrade
  - brew prune
  - brew cleanup
  - brew doctor
script:
  - set -o pipefail
  - swift package resolve
  - mkdir -p "${SRCROOT}/tmp"
  - pact-mock-service start --pact-specification-version 2.0.0 --log "${SRCROOT}/tmp/pact.log" --pact-dir "${SRCROOT}/tmp/pacts" -p 1234
  - swift build
  - pact-mock-service stop
